### ISSUE TITLE
Does MobileNetVLAD need to be distillated on a target distribution dataset?

### ISSUE THREAD

**Issue by jingedawang** [ethz-asl/hierarchical_loc#2]
I get "yes" in chapter 3.1. But in chapter 4.1, distillation uses NCLT dataset which located in The University of Michigan North Campus, while pose estimation dataset uses Google Tango in Zurich.

**Comment by Skydes** [comment]
This might be beneficial but is not necessary. We perform distillation from the Google Landmarks dataset, which is more general than the evaluation datasets (NCLT and Zurich), as it is composed of images recorded outdoors but not limited to daylight and urban environment.
