### ISSUE TITLE
Where to apply descriptor dimension reduction using PCA？

### ISSUE THREAD

**Issue by jingedawang** [ethz-asl/hierarchical_loc#3]
I am not clearly about which place the descriptor dimension reduction is located in training process of MobileNetVLAD. Is it applied to global descriptor computed by teacher network, and then use the reduced descriptor as the supervision for student network? Or other places?

Looking forward to your reply. Thanks!

**Comment by Skydes** [comment]
1) The target descriptors are PCA-reduced NetVLAD descriptors, where the PCA parameters are provided by the original authors. MobileNetVLAD additionally contains a final projection layer to match the descriptor dimensionality.

2) PCA is also computed at test time. The parameters are estimated on the descriptors of the indexed keyframes and later applied to each query descriptor.

**Comment by jingedawang** [comment]
Thanks for your reply.
One more question, is the final projection layer in MobileNetVLAD a convolutional layer? Or just a computation stage after the MobileNetVLAD network?
