### ISSUE TITLE
How to calculate triplet loss with teacher_model and student_model

### ISSUE THREAD

**Issue by YellowBe** [ethz-asl/hierarchical_loc#9]
Hello, what is the formula to  calculate the loss in mobilenetvlad with distillation? I saw in loss function there is descriptor_n and descriptor_p, where are they come from? I am sorry about i don’t understand well in where the loss get their descriptors.

**Comment by Skydes** [comment]
The loss is simply the L2 loss between the student descriptors and the teacher descriptors. The former are predicted by MobileNetVLAD while the latter are precomputed from NetVLAD. There is no triplet loss.
